version: 2

jobs:
  build-and-test:
    working_directory: ~/circleci-swpy
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install poetry
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
      - run:
          name: Run Tests, Report Coverage
          command: |
            poetry run tox
            poetry run codecov -t ${CODECOV_TOKEN}
  deploy:
    working_directory: ~/circleci-swpy
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Deploy to PyPI
          command: |
            poetry publish --build -u ${PYPI_U} -p ${PYPI_P}

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
  deploy-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
